FROM node:8

WORKDIR /usr/src/mtk

COPY package*.json ./

COPY . .

RUN npm install && \
    npm run prestart:prod

WORKDIR /usr/src/mtk/client
COPY client/package*.json ./

COPY client ./

RUN npm install && \
    npm run build

WORKDIR /usr/src/mtk

EXPOSE 3002
CMD [ "npm", "start" ]
